# Generated by Django 6.0.6 on 2026-07-02 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.TextField(default="I'm a designer-developer hybrid. I care about the pixel and the person behind the screen in equal measure.")),
                ('philosophy', models.TextField(default='Good design is honest. It removes friction, respects attention, and earns trust one interaction at a time.')),
                ('portrait', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('values', models.TextField(default='Clarity over cleverness|Users before aesthetics|Systems, not screens|Craft in the details', help_text='Values separated by | ')),
            ],
            options={
                'verbose_name': 'About section',
                'verbose_name_plural': 'About section',
            },
        ),
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('year', models.CharField(default='2025', max_length=10)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='casestudies/')),
                ('accent_hue', models.PositiveIntegerField(default=200)),
                ('featured', models.BooleanField(default=False)),
                ('summary', models.CharField(max_length=240)),
                ('research', models.TextField(blank=True)),
                ('user_flow', models.TextField(blank=True)),
                ('journey_map', models.TextField(blank=True)),
                ('design_decisions', models.TextField(blank=True)),
                ('prototype', models.TextField(blank=True)),
                ('before_after', models.TextField(blank=True, verbose_name='Before & after')),
                ('outcome', models.TextField(blank=True, verbose_name='Final outcome')),
            ],
            options={
                'verbose_name_plural': 'Case studies',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=80)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clients/')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=160)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='UI/UX Designer & UI Developer', max_length=80)),
                ('headline_line1', models.CharField(default='Designing interfaces', max_length=80)),
                ('headline_line2', models.CharField(default='people love to use.', max_length=80)),
                ('typed_roles', models.CharField(default='UI Designer,UX Designer,UI Developer,Design Systems Builder', help_text='Comma-separated roles for the typing animation.', max_length=255)),
                ('statement', models.TextField(default='I turn complex problems into clear, elegant digital products — from first research sketch to production-ready interface.')),
                ('cta_primary_label', models.CharField(default='View my work', max_length=40)),
                ('cta_primary_url', models.CharField(default='/projects/', max_length=200)),
                ('cta_secondary_label', models.CharField(default="Let's talk", max_length=40)),
                ('cta_secondary_url', models.CharField(default='/contact/', max_length=200)),
                ('portrait', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('years_experience', models.PositiveIntegerField(default=6)),
                ('projects_shipped', models.PositiveIntegerField(default=48)),
                ('happy_clients', models.PositiveIntegerField(default=32)),
            ],
            options={
                'verbose_name': 'Hero section',
                'verbose_name_plural': 'Hero section',
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=60)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Project categories',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='layout', help_text='Icon key: layout, users, layers, code, smartphone, grid, pen, monitor', max_length=40)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Alex Rivera', max_length=100)),
                ('tagline', models.CharField(default='UI/UX Designer & UI Developer', max_length=160)),
                ('email', models.EmailField(default='hello@example.com', max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('location', models.CharField(default='Kochi, India', max_length=120)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resume/')),
                ('logo_text', models.CharField(default='AR', max_length=40)),
                ('footer_note', models.CharField(default='Designed & built with care.', max_length=200)),
                ('seo_title', models.CharField(blank=True, help_text='Default <title>. Falls back to site name.', max_length=70)),
                ('seo_description', models.CharField(blank=True, max_length=160)),
                ('seo_keywords', models.CharField(blank=True, max_length=255)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/')),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'Skill categories',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('platform', models.CharField(choices=[('dribbble', 'Dribbble'), ('behance', 'Behance'), ('linkedin', 'LinkedIn'), ('github', 'GitHub'), ('twitter', 'X / Twitter'), ('instagram', 'Instagram')], max_length=20)),
                ('url', models.URLField()),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=80)),
                ('role', models.CharField(max_length=120)),
                ('quote', models.TextField()),
                ('rating', models.PositiveIntegerField(default=5)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimelineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('kind', models.CharField(choices=[('work', 'Experience'), ('education', 'Education')], default='work', max_length=12)),
                ('period', models.CharField(help_text='e.g. 2022 — Present', max_length=40)),
                ('title', models.CharField(max_length=120)),
                ('org', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Timeline entries',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('year', models.CharField(default='2025', max_length=10)),
                ('client', models.CharField(blank=True, max_length=120)),
                ('role', models.CharField(default='UI/UX Designer', max_length=120)),
                ('summary', models.CharField(max_length=240)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('accent_hue', models.PositiveIntegerField(default=252, help_text='0-360; tints the placeholder cover when no image is set')),
                ('featured', models.BooleanField(default=False)),
                ('live_url', models.URLField(blank=True)),
                ('prototype_url', models.URLField(blank=True, help_text='Figma / prototype embed link')),
                ('overview', models.TextField(blank=True)),
                ('problem', models.TextField(blank=True)),
                ('research', models.TextField(blank=True)),
                ('persona', models.TextField(blank=True, verbose_name='User persona')),
                ('wireframes', models.TextField(blank=True)),
                ('design_process', models.TextField(blank=True)),
                ('high_fidelity', models.TextField(blank=True, verbose_name='High-fidelity UI')),
                ('design_system', models.TextField(blank=True)),
                ('results', models.TextField(blank=True)),
                ('lessons', models.TextField(blank=True, verbose_name='Lessons learned')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.projectcategory')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('caption', models.CharField(blank=True, max_length=160)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.project')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=60)),
                ('level', models.PositiveIntegerField(default=90, help_text='0-100')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.skillcategory')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
