# Generated by Django 6.0.4 on 2026-07-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sitesettings_logo_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=140)),
                ('issuer', models.CharField(max_length=120)),
                ('date', models.CharField(help_text='e.g. 2023 or Jan 2023', max_length=40)),
                ('credential_url', models.URLField(blank=True, help_text='Link to verify the credential')),
            ],
            options={
                'verbose_name_plural': 'Certifications',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
